"""A destination-relative path can never resolve outside the destination root.

`LocalDestination._full` was a bare ``self._root / relative_path``, and `Path.__truediv__`
does not defend a root: an absolute right-hand side **replaces** the left entirely, and ``..``
components are carried through untouched. The invariant held only because every relative path
truestill builds ends in a `Path.name` taken from a filesystem walk, which is always a single
safe component. That is an accident of the callers, not a property of the destination.

**Deliberately lexical, and that is a departure from the usual advice.** The standard remedy is
``resolve()`` plus ``is_relative_to()``, which is wrong here: ``resolve()`` follows symlinks, so
a library with a year folder symlinked onto a second disk would resolve outside its own root and
be **falsely refused**. The threat model differs from a web server's too - the relative path is
generated by truestill from a filesystem walk, never supplied by an untrusted caller. So the
check reads the string, touches no filesystem, and refuses the three shapes that can escape.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from truestill_core.destinations.base import DestinationError, check_contained
from truestill_core.destinations.local import LocalDestination

#: Every shape that can leave the root. Each is a *different* mechanism, not a spelling of one.
ESCAPES = [
    ("parent traversal", "../outside.jpg"),
    ("traversal mid-path", "Camera/../../outside.jpg"),
    ("bare parent", ".."),
    ("posix absolute", "/etc/passwd"),
    ("windows absolute", "C:/Windows/system32/x.dll"),
    ("windows drive-relative", "C:x.dll"),
    ("windows backslash traversal", r"..\outside.jpg"),
    ("unc path", "//server/share/x.jpg"),
]

#: Paths that must keep working. A guard that refuses these gets switched off (§4, cry-wolf).
LEGITIMATE = [
    "IMG_0001.jpg",
    "2014/2014-08/2014-08 - Everyday/20140815_143022_IMG_0001.jpg",
    "WhatsApp/2025/2025-08/VID-20250804-WA0020.mp4",
    "Camera/a file with spaces.jpg",
    "Undated/....hidden.jpg",
    "2014/2014-08/Mr. Smith's Trip/x.jpg",
    "Ünïcødé/日本語/x.jpg",
    "a/b/c/d/e/f/g/deeply nested.jpg",
]


@pytest.mark.parametrize(("label", "relative"), ESCAPES)
def test_a_relative_path_that_could_leave_the_root_is_refused(label: str, relative: str) -> None:
    with pytest.raises(DestinationError) as raised:
        check_contained(relative)
    # `repr`, because the message quotes the path with `!r` -- a backslash is escaped there.
    assert repr(relative) in str(raised.value), label


@pytest.mark.parametrize("relative", LEGITIMATE)
def test_an_ordinary_relative_path_is_allowed(relative: str) -> None:
    """Cry-wolf half. These are the paths the product actually generates."""
    check_contained(relative)


@pytest.mark.parametrize(("label", "relative"), ESCAPES)
def test_the_local_destination_refuses_before_touching_the_filesystem(
    label: str, relative: str, tmp_path: Path
) -> None:
    """The guard must sit on the destination, not only in a helper nobody is obliged to call."""
    destination = LocalDestination(tmp_path / "library")
    with pytest.raises(DestinationError):
        destination.exists(relative)
    with pytest.raises(DestinationError):
        destination.upload(tmp_path / "anything.jpg", relative)
    assert label, "every escape shape is named, so a failure says which mechanism it was"


def test_a_symlinked_subfolder_is_not_refused(tmp_path: Path) -> None:
    """The reason this check is lexical rather than `resolve()`-based, pinned as a test.

    A year folder living on a second disk is an ordinary setup. Under `resolve()` plus
    `is_relative_to()` it resolves outside the root and would be refused, which would break
    real libraries in the name of a threat we do not have.
    """
    root = tmp_path / "library"
    elsewhere = tmp_path / "second-disk" / "2014"
    elsewhere.mkdir(parents=True)
    root.mkdir()
    (root / "2014").symlink_to(elsewhere, target_is_directory=True)

    destination = LocalDestination(root)
    source = tmp_path / "photo.jpg"
    source.write_bytes(b"\xff\xd8 photo")
    destination.upload(source, "2014/IMG_0001.jpg")

    assert (elsewhere / "IMG_0001.jpg").read_bytes() == b"\xff\xd8 photo"


def test_the_refusal_names_the_path_and_does_not_write(tmp_path: Path) -> None:
    """Never-silent, and never a partial write: nothing lands before the refusal."""
    root = tmp_path / "library"
    root.mkdir()
    source = tmp_path / "photo.jpg"
    source.write_bytes(b"\xff\xd8 photo")
    outside = tmp_path / "outside.jpg"

    with pytest.raises(DestinationError) as raised:
        LocalDestination(root).upload(source, "../outside.jpg")

    assert repr("../outside.jpg") in str(raised.value)
    assert not outside.exists()
    assert list(root.iterdir()) == []
