import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/**
 * A CONTENT hash of everything that decides the bundle's bytes - never an mtime.
 *
 * The guard this feeds asks "were the served bytes built from the sources on disk right now".
 * A timestamp cannot answer that: `ENGINEERING_STANDARD.md` §4's forty-ninth member is a whole
 * worked example of mtime granularity defeating a freshness check, where a same-second, same-size
 * restore left Python running a mutant. So the inputs are hashed, and the digest is baked into
 * the bundle for `test_the_served_bundle_was_built_from_these_sources` to compare against.
 *
 * The algorithm is deliberately trivial - sorted relative path, NUL, bytes, NUL - because a
 * Python implementation has to agree with it exactly, and two clever implementations agree less
 * often than two boring ones.
 */
const HASHED = ["src", "vite.config.ts", "package.json", "package-lock.json"];

function walk(path: string, out: string[] = []): string[] {
  if (statSync(path).isDirectory()) {
    for (const entry of readdirSync(path).sort()) walk(join(path, entry), out);
  } else {
    out.push(path);
  }
  return out;
}

function sourceHash(): string {
  const files: string[] = [];
  for (const target of HASHED) {
    try {
      walk(target, files);
    } catch {
      // package-lock.json is absent on a fresh checkout until `npm install`; the Python side
      // skips it identically, so the two stay in step rather than silently diverging.
    }
  }
  const digest = createHash("sha256");
  for (const file of files.map((f) => relative(".", f)).sort()) {
    digest.update(file.split(sep).join("/"));
    digest.update("\0");
    digest.update(readFileSync(file));
    digest.update("\0");
  }
  return digest.digest("hex").slice(0, 16);
}

export default defineConfig({
  plugins: [react()],
  define: { __BUNDLE_SOURCE_HASH__: JSON.stringify(sourceHash()) },
  build: {
    // Into the directory Starlette already mounts, so nothing new serves anything: the bundle
    // travels with `static/` exactly as the bundled fonts do.
    outDir: "../src/truestill_app/static/dist",
    emptyOutDir: true,
    target: "es2022",
    rollupOptions: {
      input: "src/main.tsx",
      // A FIXED name, not a hash. The page is served by Jinja, not generated by Vite, so a
      // hashed filename would need a manifest read on the Python side for no benefit the
      // existing static fingerprint does not already provide.
      output: { entryFileNames: "main.js", assetFileNames: "[name][extname]" },
    },
  },
});
